name: ikea_assembly_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - Versions compatibles
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.2
  cloud_firestore: ^5.6.12
  provider: ^6.1.5+1
  google_sign_in: ^7.2.0
  model_viewer_plus: ^1.4.0

dev_dependencies:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/malm_bed.glb
    - assets/models/pahl_desk.glb
    - assets/models/poang_armchair.glb
    - assets/models/pax_wardrobe.glb
    - assets/models/lack_table.glb
    - assets/models/ikea_hemnes_dresser.glb
    - assets/models/ikea_raskog_pink_utility_trolley.glb
    - assets/models/ikea_fjallbo_tv_unit.glb
    - assets/models/corner_sofa.glb
    - assets/models/ikea_bissa_shoe_storage_rigged.glb
    - assets/models/sofa_-_ikea_nockeby.glb

